//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5448
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using System.Net;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 

namespace INIKER.FSubcontratacion
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "Subcontratacion_Binding", Namespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion")]
    public partial class Subcontratacion : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback TraerLineasPedidoKilosOperationCompleted;

        private System.Threading.SendOrPostCallback ClienteSubcontratadoOperationCompleted;

        private System.Threading.SendOrPostCallback CrearPedidosCompraOperationCompleted;

        private System.Threading.SendOrPostCallback ACosturaSubcOperationCompleted;

        private System.Threading.SendOrPostCallback SalidaCosturaOperationCompleted;

        private System.Threading.SendOrPostCallback GenerarPedidoCompraOperationCompleted;

        private System.Threading.SendOrPostCallback GenerarLineaPedidoCompraOperationCompleted;

        private System.Threading.SendOrPostCallback EliminarPedidoCompraOperationCompleted;

        private System.Threading.SendOrPostCallback EliminarLineaPedidoCompraOperationCompleted;

        private System.Threading.SendOrPostCallback LanzarPedidoCompraOperationCompleted;

        private System.Threading.SendOrPostCallback RegistrarPedidoCompraOperationCompleted;

        private System.Threading.SendOrPostCallback DeshacerAlbaranVentaOperationCompleted;

        private System.Threading.SendOrPostCallback SubcontratarClienteOperationCompleted;

        private System.Threading.SendOrPostCallback ProcesarMovsProduccionOperationCompleted;

        private System.Threading.SendOrPostCallback ExisteLineaPedidoKilosOperationCompleted;

        private System.Threading.SendOrPostCallback EliminarLineasPedidoCompraOperationCompleted;

        /// <remarks/>
        public Subcontratacion()
        {
            EntidadesSubcontratacion.Properties.Settings miConfig = new EntidadesSubcontratacion.Properties.Settings();
            this.Url = miConfig.urlInicioDefaultWS + "/Codeunit/Subcontratacion?WSDL";
            this.UseDefaultCredentials = true;
            //this.Url = "http://serv-nsql2008:7047/GINDUSAL/WS/02 NAVARRA/Page/ClientesSubcontratados?WSDL";
            //this.Credentials = new NetworkCredential("JCA", "Iniker1");
        }

        public Subcontratacion(string IDusuario, string pwd)
        {
            // Este constructor se utiliza para obtener el nombre de la empresa con la que
            // trabaja el usuario que ha hecho login en el equipo.
            EntidadesSubcontratacion.Properties.Settings miConfig = new EntidadesSubcontratacion.Properties.Settings();
            this.Url = miConfig.urlInicioWS + "/Codeunit/Subcontratacion?WSDL";
            if (miConfig.useDefCredts)
                this.UseDefaultCredentials = true;
            else
                this.Credentials = new NetworkCredential(IDusuario, pwd);
        }

        public Subcontratacion(string IDusuario, string pwd, string empresa)
        {
            // Constructor para trabajar contra los web services una vez obtenida la empresa de trabajo
            EntidadesSubcontratacion.Properties.Settings miConfig = new EntidadesSubcontratacion.Properties.Settings();
            this.Url = miConfig.urlInicioWS + "/" + empresa + "/Codeunit/Subcontratacion?WSDL";
            if (miConfig.useDefCredts)
                this.UseDefaultCredentials = true;
            else
                this.Credentials = new NetworkCredential(IDusuario, pwd);
        }

        /// <remarks/>
        public event TraerLineasPedidoKilosCompletedEventHandler TraerLineasPedidoKilosCompleted;

        /// <remarks/>
        public event ClienteSubcontratadoCompletedEventHandler ClienteSubcontratadoCompleted;

        /// <remarks/>
        public event CrearPedidosCompraCompletedEventHandler CrearPedidosCompraCompleted;

        /// <remarks/>
        public event ACosturaSubcCompletedEventHandler ACosturaSubcCompleted;

        /// <remarks/>
        public event SalidaCosturaCompletedEventHandler SalidaCosturaCompleted;

        /// <remarks/>
        public event GenerarPedidoCompraCompletedEventHandler GenerarPedidoCompraCompleted;

        /// <remarks/>
        public event GenerarLineaPedidoCompraCompletedEventHandler GenerarLineaPedidoCompraCompleted;

        /// <remarks/>
        public event EliminarPedidoCompraCompletedEventHandler EliminarPedidoCompraCompleted;

        /// <remarks/>
        public event EliminarLineaPedidoCompraCompletedEventHandler EliminarLineaPedidoCompraCompleted;

        /// <remarks/>
        public event LanzarPedidoCompraCompletedEventHandler LanzarPedidoCompraCompleted;

        /// <remarks/>
        public event RegistrarPedidoCompraCompletedEventHandler RegistrarPedidoCompraCompleted;

        /// <remarks/>
        public event DeshacerAlbaranVentaCompletedEventHandler DeshacerAlbaranVentaCompleted;

        /// <remarks/>
        public event SubcontratarClienteCompletedEventHandler SubcontratarClienteCompleted;

        /// <remarks/>
        public event ProcesarMovsProduccionCompletedEventHandler ProcesarMovsProduccionCompleted;

        /// <remarks/>
        public event ExisteLineaPedidoKilosCompletedEventHandler ExisteLineaPedidoKilosCompleted;

        /// <remarks/>
        public event EliminarLineasPedidoCompraCompletedEventHandler EliminarLineasPedidoCompraCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:TraerLineasPedidoKilos", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "TraerLineasPedidoKilos_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TraerLineasPedidoKilos(string nPedidoOrigen, string empresaOrigen, string nPedidoDestino)
        {
            this.Invoke("TraerLineasPedidoKilos", new object[] {
                    nPedidoOrigen,
                    empresaOrigen,
                    nPedidoDestino});
        }

        /// <remarks/>
        public System.IAsyncResult BeginTraerLineasPedidoKilos(string nPedidoOrigen, string empresaOrigen, string nPedidoDestino, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("TraerLineasPedidoKilos", new object[] {
                    nPedidoOrigen,
                    empresaOrigen,
                    nPedidoDestino}, callback, asyncState);
        }

        /// <remarks/>
        public void EndTraerLineasPedidoKilos(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void TraerLineasPedidoKilosAsync(string nPedidoOrigen, string empresaOrigen, string nPedidoDestino)
        {
            this.TraerLineasPedidoKilosAsync(nPedidoOrigen, empresaOrigen, nPedidoDestino, null);
        }

        /// <remarks/>
        public void TraerLineasPedidoKilosAsync(string nPedidoOrigen, string empresaOrigen, string nPedidoDestino, object userState)
        {
            if ((this.TraerLineasPedidoKilosOperationCompleted == null))
            {
                this.TraerLineasPedidoKilosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraerLineasPedidoKilosOperationCompleted);
            }
            this.InvokeAsync("TraerLineasPedidoKilos", new object[] {
                    nPedidoOrigen,
                    empresaOrigen,
                    nPedidoDestino}, this.TraerLineasPedidoKilosOperationCompleted, userState);
        }

        private void OnTraerLineasPedidoKilosOperationCompleted(object arg)
        {
            if ((this.TraerLineasPedidoKilosCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraerLineasPedidoKilosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:ClienteSubcontratado", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "ClienteSubcontratado_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string ClienteSubcontratado(string cliente)
        {
            object[] results = this.Invoke("ClienteSubcontratado", new object[] {
                    cliente});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginClienteSubcontratado(string cliente, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ClienteSubcontratado", new object[] {
                    cliente}, callback, asyncState);
        }

        /// <remarks/>
        public string EndClienteSubcontratado(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ClienteSubcontratadoAsync(string cliente)
        {
            this.ClienteSubcontratadoAsync(cliente, null);
        }

        /// <remarks/>
        public void ClienteSubcontratadoAsync(string cliente, object userState)
        {
            if ((this.ClienteSubcontratadoOperationCompleted == null))
            {
                this.ClienteSubcontratadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClienteSubcontratadoOperationCompleted);
            }
            this.InvokeAsync("ClienteSubcontratado", new object[] {
                    cliente}, this.ClienteSubcontratadoOperationCompleted, userState);
        }

        private void OnClienteSubcontratadoOperationCompleted(object arg)
        {
            if ((this.ClienteSubcontratadoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClienteSubcontratadoCompleted(this, new ClienteSubcontratadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:CrearPedidosCompra", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "CrearPedidosCompra_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CrearPedidosCompra()
        {
            this.Invoke("CrearPedidosCompra", new object[0]);
        }

        /// <remarks/>
        public System.IAsyncResult BeginCrearPedidosCompra(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CrearPedidosCompra", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public void EndCrearPedidosCompra(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void CrearPedidosCompraAsync()
        {
            this.CrearPedidosCompraAsync(null);
        }

        /// <remarks/>
        public void CrearPedidosCompraAsync(object userState)
        {
            if ((this.CrearPedidosCompraOperationCompleted == null))
            {
                this.CrearPedidosCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearPedidosCompraOperationCompleted);
            }
            this.InvokeAsync("CrearPedidosCompra", new object[0], this.CrearPedidosCompraOperationCompleted, userState);
        }

        private void OnCrearPedidosCompraOperationCompleted(object arg)
        {
            if ((this.CrearPedidosCompraCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearPedidosCompraCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:ACosturaSubc", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "ACosturaSubc_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ACosturaSubc(string cliente, string producto, int uds)
        {
            this.Invoke("ACosturaSubc", new object[] {
                    cliente,
                    producto,
                    uds});
        }

        /// <remarks/>
        public System.IAsyncResult BeginACosturaSubc(string cliente, string producto, int uds, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ACosturaSubc", new object[] {
                    cliente,
                    producto,
                    uds}, callback, asyncState);
        }

        /// <remarks/>
        public void EndACosturaSubc(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void ACosturaSubcAsync(string cliente, string producto, int uds)
        {
            this.ACosturaSubcAsync(cliente, producto, uds, null);
        }

        /// <remarks/>
        public void ACosturaSubcAsync(string cliente, string producto, int uds, object userState)
        {
            if ((this.ACosturaSubcOperationCompleted == null))
            {
                this.ACosturaSubcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnACosturaSubcOperationCompleted);
            }
            this.InvokeAsync("ACosturaSubc", new object[] {
                    cliente,
                    producto,
                    uds}, this.ACosturaSubcOperationCompleted, userState);
        }

        private void OnACosturaSubcOperationCompleted(object arg)
        {
            if ((this.ACosturaSubcCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ACosturaSubcCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:SalidaCostura", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "SalidaCostura_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SalidaCostura(string cliente, string producto, int uds)
        {
            this.Invoke("SalidaCostura", new object[] {
                    cliente,
                    producto,
                    uds});
        }

        /// <remarks/>
        public System.IAsyncResult BeginSalidaCostura(string cliente, string producto, int uds, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SalidaCostura", new object[] {
                    cliente,
                    producto,
                    uds}, callback, asyncState);
        }

        /// <remarks/>
        public void EndSalidaCostura(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void SalidaCosturaAsync(string cliente, string producto, int uds)
        {
            this.SalidaCosturaAsync(cliente, producto, uds, null);
        }

        /// <remarks/>
        public void SalidaCosturaAsync(string cliente, string producto, int uds, object userState)
        {
            if ((this.SalidaCosturaOperationCompleted == null))
            {
                this.SalidaCosturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSalidaCosturaOperationCompleted);
            }
            this.InvokeAsync("SalidaCostura", new object[] {
                    cliente,
                    producto,
                    uds}, this.SalidaCosturaOperationCompleted, userState);
        }

        private void OnSalidaCosturaOperationCompleted(object arg)
        {
            if ((this.SalidaCosturaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SalidaCosturaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:GenerarPedidoCompra", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "GenerarPedidoCompra_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GenerarPedidoCompra(string proveedor, string clienteFinal, [System.Xml.Serialization.XmlElementAttribute(DataType = "date")] System.DateTime fRegistro)
        {
            object[] results = this.Invoke("GenerarPedidoCompra", new object[] {
                    proveedor,
                    clienteFinal,
                    fRegistro});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGenerarPedidoCompra(string proveedor, string clienteFinal, System.DateTime fRegistro, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GenerarPedidoCompra", new object[] {
                    proveedor,
                    clienteFinal,
                    fRegistro}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGenerarPedidoCompra(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GenerarPedidoCompraAsync(string proveedor, string clienteFinal, System.DateTime fRegistro)
        {
            this.GenerarPedidoCompraAsync(proveedor, clienteFinal, fRegistro, null);
        }

        /// <remarks/>
        public void GenerarPedidoCompraAsync(string proveedor, string clienteFinal, System.DateTime fRegistro, object userState)
        {
            if ((this.GenerarPedidoCompraOperationCompleted == null))
            {
                this.GenerarPedidoCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarPedidoCompraOperationCompleted);
            }
            this.InvokeAsync("GenerarPedidoCompra", new object[] {
                    proveedor,
                    clienteFinal,
                    fRegistro}, this.GenerarPedidoCompraOperationCompleted, userState);
        }

        private void OnGenerarPedidoCompraOperationCompleted(object arg)
        {
            if ((this.GenerarPedidoCompraCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarPedidoCompraCompleted(this, new GenerarPedidoCompraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:GenerarLineaPedidoCompra", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "GenerarLineaPedidoCompra_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerarLineaPedidoCompra(string pedido, string proveedor, string producto, decimal cantidad)
        {
            this.Invoke("GenerarLineaPedidoCompra", new object[] {
                    pedido,
                    proveedor,
                    producto,
                    cantidad});
        }

        /// <remarks/>
        public System.IAsyncResult BeginGenerarLineaPedidoCompra(string pedido, string proveedor, string producto, decimal cantidad, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GenerarLineaPedidoCompra", new object[] {
                    pedido,
                    proveedor,
                    producto,
                    cantidad}, callback, asyncState);
        }

        /// <remarks/>
        public void EndGenerarLineaPedidoCompra(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void GenerarLineaPedidoCompraAsync(string pedido, string proveedor, string producto, decimal cantidad)
        {
            this.GenerarLineaPedidoCompraAsync(pedido, proveedor, producto, cantidad, null);
        }

        /// <remarks/>
        public void GenerarLineaPedidoCompraAsync(string pedido, string proveedor, string producto, decimal cantidad, object userState)
        {
            if ((this.GenerarLineaPedidoCompraOperationCompleted == null))
            {
                this.GenerarLineaPedidoCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarLineaPedidoCompraOperationCompleted);
            }
            this.InvokeAsync("GenerarLineaPedidoCompra", new object[] {
                    pedido,
                    proveedor,
                    producto,
                    cantidad}, this.GenerarLineaPedidoCompraOperationCompleted, userState);
        }

        private void OnGenerarLineaPedidoCompraOperationCompleted(object arg)
        {
            if ((this.GenerarLineaPedidoCompraCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarLineaPedidoCompraCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:EliminarPedidoCompra", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "EliminarPedidoCompra_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarPedidoCompra(string numero)
        {
            this.Invoke("EliminarPedidoCompra", new object[] {
                    numero});
        }

        /// <remarks/>
        public System.IAsyncResult BeginEliminarPedidoCompra(string numero, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EliminarPedidoCompra", new object[] {
                    numero}, callback, asyncState);
        }

        /// <remarks/>
        public void EndEliminarPedidoCompra(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void EliminarPedidoCompraAsync(string numero)
        {
            this.EliminarPedidoCompraAsync(numero, null);
        }

        /// <remarks/>
        public void EliminarPedidoCompraAsync(string numero, object userState)
        {
            if ((this.EliminarPedidoCompraOperationCompleted == null))
            {
                this.EliminarPedidoCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarPedidoCompraOperationCompleted);
            }
            this.InvokeAsync("EliminarPedidoCompra", new object[] {
                    numero}, this.EliminarPedidoCompraOperationCompleted, userState);
        }

        private void OnEliminarPedidoCompraOperationCompleted(object arg)
        {
            if ((this.EliminarPedidoCompraCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarPedidoCompraCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:EliminarLineaPedidoCompra" +
            "", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "EliminarLineaPedidoCompra_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarLineaPedidoCompra(string pedido, int linea)
        {
            this.Invoke("EliminarLineaPedidoCompra", new object[] {
                    pedido,
                    linea});
        }

        /// <remarks/>
        public System.IAsyncResult BeginEliminarLineaPedidoCompra(string pedido, int linea, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EliminarLineaPedidoCompra", new object[] {
                    pedido,
                    linea}, callback, asyncState);
        }

        /// <remarks/>
        public void EndEliminarLineaPedidoCompra(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void EliminarLineaPedidoCompraAsync(string pedido, int linea)
        {
            this.EliminarLineaPedidoCompraAsync(pedido, linea, null);
        }

        /// <remarks/>
        public void EliminarLineaPedidoCompraAsync(string pedido, int linea, object userState)
        {
            if ((this.EliminarLineaPedidoCompraOperationCompleted == null))
            {
                this.EliminarLineaPedidoCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarLineaPedidoCompraOperationCompleted);
            }
            this.InvokeAsync("EliminarLineaPedidoCompra", new object[] {
                    pedido,
                    linea}, this.EliminarLineaPedidoCompraOperationCompleted, userState);
        }

        private void OnEliminarLineaPedidoCompraOperationCompleted(object arg)
        {
            if ((this.EliminarLineaPedidoCompraCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarLineaPedidoCompraCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:LanzarPedidoCompra", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "LanzarPedidoCompra_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string LanzarPedidoCompra(string numero)
        {
            object[] results = this.Invoke("LanzarPedidoCompra", new object[] {
                    numero});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginLanzarPedidoCompra(string numero, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("LanzarPedidoCompra", new object[] {
                    numero}, callback, asyncState);
        }

        /// <remarks/>
        public string EndLanzarPedidoCompra(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void LanzarPedidoCompraAsync(string numero)
        {
            this.LanzarPedidoCompraAsync(numero, null);
        }

        /// <remarks/>
        public void LanzarPedidoCompraAsync(string numero, object userState)
        {
            if ((this.LanzarPedidoCompraOperationCompleted == null))
            {
                this.LanzarPedidoCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLanzarPedidoCompraOperationCompleted);
            }
            this.InvokeAsync("LanzarPedidoCompra", new object[] {
                    numero}, this.LanzarPedidoCompraOperationCompleted, userState);
        }

        private void OnLanzarPedidoCompraOperationCompleted(object arg)
        {
            if ((this.LanzarPedidoCompraCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LanzarPedidoCompraCompleted(this, new LanzarPedidoCompraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:RegistrarPedidoCompra", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "RegistrarPedidoCompra_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string RegistrarPedidoCompra(string numero)
        {
            object[] results = this.Invoke("RegistrarPedidoCompra", new object[] {
                    numero});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginRegistrarPedidoCompra(string numero, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("RegistrarPedidoCompra", new object[] {
                    numero}, callback, asyncState);
        }

        /// <remarks/>
        public string EndRegistrarPedidoCompra(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void RegistrarPedidoCompraAsync(string numero)
        {
            this.RegistrarPedidoCompraAsync(numero, null);
        }

        /// <remarks/>
        public void RegistrarPedidoCompraAsync(string numero, object userState)
        {
            if ((this.RegistrarPedidoCompraOperationCompleted == null))
            {
                this.RegistrarPedidoCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarPedidoCompraOperationCompleted);
            }
            this.InvokeAsync("RegistrarPedidoCompra", new object[] {
                    numero}, this.RegistrarPedidoCompraOperationCompleted, userState);
        }

        private void OnRegistrarPedidoCompraOperationCompleted(object arg)
        {
            if ((this.RegistrarPedidoCompraCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarPedidoCompraCompleted(this, new RegistrarPedidoCompraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:DeshacerAlbaranVenta", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "DeshacerAlbaranVenta_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeshacerAlbaranVenta(string salesShptNo)
        {
            this.Invoke("DeshacerAlbaranVenta", new object[] {
                    salesShptNo});
        }

        /// <remarks/>
        public System.IAsyncResult BeginDeshacerAlbaranVenta(string salesShptNo, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DeshacerAlbaranVenta", new object[] {
                    salesShptNo}, callback, asyncState);
        }

        /// <remarks/>
        public void EndDeshacerAlbaranVenta(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void DeshacerAlbaranVentaAsync(string salesShptNo)
        {
            this.DeshacerAlbaranVentaAsync(salesShptNo, null);
        }

        /// <remarks/>
        public void DeshacerAlbaranVentaAsync(string salesShptNo, object userState)
        {
            if ((this.DeshacerAlbaranVentaOperationCompleted == null))
            {
                this.DeshacerAlbaranVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeshacerAlbaranVentaOperationCompleted);
            }
            this.InvokeAsync("DeshacerAlbaranVenta", new object[] {
                    salesShptNo}, this.DeshacerAlbaranVentaOperationCompleted, userState);
        }

        private void OnDeshacerAlbaranVentaOperationCompleted(object arg)
        {
            if ((this.DeshacerAlbaranVentaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeshacerAlbaranVentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:SubcontratarCliente", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "SubcontratarCliente_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SubcontratarCliente(string customerNo)
        {
            this.Invoke("SubcontratarCliente", new object[] {
                    customerNo});
        }

        /// <remarks/>
        public System.IAsyncResult BeginSubcontratarCliente(string customerNo, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SubcontratarCliente", new object[] {
                    customerNo}, callback, asyncState);
        }

        /// <remarks/>
        public void EndSubcontratarCliente(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void SubcontratarClienteAsync(string customerNo)
        {
            this.SubcontratarClienteAsync(customerNo, null);
        }

        /// <remarks/>
        public void SubcontratarClienteAsync(string customerNo, object userState)
        {
            if ((this.SubcontratarClienteOperationCompleted == null))
            {
                this.SubcontratarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubcontratarClienteOperationCompleted);
            }
            this.InvokeAsync("SubcontratarCliente", new object[] {
                    customerNo}, this.SubcontratarClienteOperationCompleted, userState);
        }

        private void OnSubcontratarClienteOperationCompleted(object arg)
        {
            if ((this.SubcontratarClienteCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubcontratarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:ProcesarMovsProduccion", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "ProcesarMovsProduccion_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ProcesarMovsProduccion(string codCliente)
        {
            this.Invoke("ProcesarMovsProduccion", new object[] {
                    codCliente});
        }

        /// <remarks/>
        public System.IAsyncResult BeginProcesarMovsProduccion(string codCliente, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ProcesarMovsProduccion", new object[] {
                    codCliente}, callback, asyncState);
        }

        /// <remarks/>
        public void EndProcesarMovsProduccion(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void ProcesarMovsProduccionAsync(string codCliente)
        {
            this.ProcesarMovsProduccionAsync(codCliente, null);
        }

        /// <remarks/>
        public void ProcesarMovsProduccionAsync(string codCliente, object userState)
        {
            if ((this.ProcesarMovsProduccionOperationCompleted == null))
            {
                this.ProcesarMovsProduccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesarMovsProduccionOperationCompleted);
            }
            this.InvokeAsync("ProcesarMovsProduccion", new object[] {
                    codCliente}, this.ProcesarMovsProduccionOperationCompleted, userState);
        }

        private void OnProcesarMovsProduccionOperationCompleted(object arg)
        {
            if ((this.ProcesarMovsProduccionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcesarMovsProduccionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:ExisteLineaPedidoKilos", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "ExisteLineaPedidoKilos_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool ExisteLineaPedidoKilos(string nPedido)
        {
            object[] results = this.Invoke("ExisteLineaPedidoKilos", new object[] {
                    nPedido});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginExisteLineaPedidoKilos(string nPedido, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ExisteLineaPedidoKilos", new object[] {
                    nPedido}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndExisteLineaPedidoKilos(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void ExisteLineaPedidoKilosAsync(string nPedido)
        {
            this.ExisteLineaPedidoKilosAsync(nPedido, null);
        }

        /// <remarks/>
        public void ExisteLineaPedidoKilosAsync(string nPedido, object userState)
        {
            if ((this.ExisteLineaPedidoKilosOperationCompleted == null))
            {
                this.ExisteLineaPedidoKilosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExisteLineaPedidoKilosOperationCompleted);
            }
            this.InvokeAsync("ExisteLineaPedidoKilos", new object[] {
                    nPedido}, this.ExisteLineaPedidoKilosOperationCompleted, userState);
        }

        private void OnExisteLineaPedidoKilosOperationCompleted(object arg)
        {
            if ((this.ExisteLineaPedidoKilosCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExisteLineaPedidoKilosCompleted(this, new ExisteLineaPedidoKilosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Subcontratacion:EliminarLineasPedidoCompr" +
            "a", RequestNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", ResponseElementName = "EliminarLineasPedidoCompra_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/codeunit/Subcontratacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarLineasPedidoCompra(string _orderNo)
        {
            this.Invoke("EliminarLineasPedidoCompra", new object[] {
                    _orderNo});
        }

        /// <remarks/>
        public System.IAsyncResult BeginEliminarLineasPedidoCompra(string _orderNo, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EliminarLineasPedidoCompra", new object[] {
                    _orderNo}, callback, asyncState);
        }

        /// <remarks/>
        public void EndEliminarLineasPedidoCompra(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void EliminarLineasPedidoCompraAsync(string _orderNo)
        {
            this.EliminarLineasPedidoCompraAsync(_orderNo, null);
        }

        /// <remarks/>
        public void EliminarLineasPedidoCompraAsync(string _orderNo, object userState)
        {
            if ((this.EliminarLineasPedidoCompraOperationCompleted == null))
            {
                this.EliminarLineasPedidoCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarLineasPedidoCompraOperationCompleted);
            }
            this.InvokeAsync("EliminarLineasPedidoCompra", new object[] {
                    _orderNo}, this.EliminarLineasPedidoCompraOperationCompleted, userState);
        }

        private void OnEliminarLineasPedidoCompraOperationCompleted(object arg)
        {
            if ((this.EliminarLineasPedidoCompraCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarLineasPedidoCompraCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void TraerLineasPedidoKilosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ClienteSubcontratadoCompletedEventHandler(object sender, ClienteSubcontratadoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClienteSubcontratadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ClienteSubcontratadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void CrearPedidosCompraCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ACosturaSubcCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void SalidaCosturaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GenerarPedidoCompraCompletedEventHandler(object sender, GenerarPedidoCompraCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarPedidoCompraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GenerarPedidoCompraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GenerarLineaPedidoCompraCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void EliminarPedidoCompraCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void EliminarLineaPedidoCompraCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void LanzarPedidoCompraCompletedEventHandler(object sender, LanzarPedidoCompraCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LanzarPedidoCompraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal LanzarPedidoCompraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void RegistrarPedidoCompraCompletedEventHandler(object sender, RegistrarPedidoCompraCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarPedidoCompraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RegistrarPedidoCompraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void DeshacerAlbaranVentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void SubcontratarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ProcesarMovsProduccionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ExisteLineaPedidoKilosCompletedEventHandler(object sender, ExisteLineaPedidoKilosCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExisteLineaPedidoKilosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ExisteLineaPedidoKilosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void EliminarLineasPedidoCompraCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}