//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConectarWS.CodeunitWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PruebasWS_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/PruebasWS")]
    public partial class PruebasWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LLamarWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback PruebasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PruebasWS() {
            this.Url = global::ConectarWS.Properties.Settings.Default.ConectarWS_WebReference_pruebasWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LLamarWSCompletedEventHandler LLamarWSCompleted;
        
        /// <remarks/>
        public event PruebasCompletedEventHandler PruebasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PruebasWS:LLamarWS", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PruebasWS", ResponseElementName="LLamarWS_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PruebasWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LLamarWS(ref prbgve xmlOne) {
            object[] results = this.Invoke("LLamarWS", new object[] {
                        xmlOne});
            xmlOne = ((prbgve)(results[0]));
        }
        
        /// <remarks/>
        public void LLamarWSAsync(prbgve xmlOne) {
            this.LLamarWSAsync(xmlOne, null);
        }
        
        /// <remarks/>
        public void LLamarWSAsync(prbgve xmlOne, object userState) {
            if ((this.LLamarWSOperationCompleted == null)) {
                this.LLamarWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLLamarWSOperationCompleted);
            }
            this.InvokeAsync("LLamarWS", new object[] {
                        xmlOne}, this.LLamarWSOperationCompleted, userState);
        }
        
        private void OnLLamarWSOperationCompleted(object arg) {
            if ((this.LLamarWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LLamarWSCompleted(this, new LLamarWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PruebasWS:Pruebas", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PruebasWS", ResponseElementName="Pruebas_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PruebasWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Pruebas(ref string txtParam) {
            object[] results = this.Invoke("Pruebas", new object[] {
                        txtParam});
            txtParam = ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PruebasAsync(string txtParam) {
            this.PruebasAsync(txtParam, null);
        }
        
        /// <remarks/>
        public void PruebasAsync(string txtParam, object userState) {
            if ((this.PruebasOperationCompleted == null)) {
                this.PruebasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPruebasOperationCompleted);
            }
            this.InvokeAsync("Pruebas", new object[] {
                        txtParam}, this.PruebasOperationCompleted, userState);
        }
        
        private void OnPruebasOperationCompleted(object arg) {
            if ((this.PruebasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PruebasCompleted(this, new PruebasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x99997")]
    public partial class prbgve {
        
        private SD[] sdField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SD")]
        public SD[] SD {
            get {
                return this.sdField;
            }
            set {
                this.sdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x99997")]
    public partial class SD {
        
        private string nameField;
        
        private string addressField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LLamarWSCompletedEventHandler(object sender, LLamarWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LLamarWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LLamarWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public prbgve xmlOne {
            get {
                this.RaiseExceptionIfNecessary();
                return ((prbgve)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void PruebasCompletedEventHandler(object sender, PruebasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PruebasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PruebasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string txtParam {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591