//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3603
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using System.Net;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 

namespace INIKER.MovsProduccion
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "MovsProdSinRegINDUSAL_Binding", Namespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal")]
    public partial class MovsProdSinRegINDUSAL_Service : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ReadOperationCompleted;

        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;

        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;

        private System.Threading.SendOrPostCallback CreateOperationCompleted;

        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;

        private System.Threading.SendOrPostCallback UpdateOperationCompleted;

        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;

        private System.Threading.SendOrPostCallback DeleteOperationCompleted;

        /// <remarks/>
        public MovsProdSinRegINDUSAL_Service()
        {
            Entidades.Properties.Settings miConfig = new Entidades.Properties.Settings();
            this.Url = miConfig.urlInicioDefaultWS + "/Page/MovsProdSinRegINDUSAL?WSDL";
            this.UseDefaultCredentials = true;

            //this.Url = "http://serv-nsql2008:7047/GINDUSAL/WS/02 NAVARRA/Page/MovsProdSinRegINDUSAL?WSDL";
            //this.Credentials = new NetworkCredential("JCA", "Iniker1");
        }

        public MovsProdSinRegINDUSAL_Service(string IDusuario, string pwd)
        {
            // Este constructor se utiliza para obtener el nombre de la empresa con la que
            // trabaja el usuario que ha hecho login en el equipo.
            Entidades.Properties.Settings miConfig = new Entidades.Properties.Settings();
            this.Url = miConfig.urlInicioWS + "/Page/MovsProdSinRegINDUSAL?WSDL";
            if (miConfig.useDefCredts)
                this.UseDefaultCredentials = true;
            else
                this.Credentials = new NetworkCredential(IDusuario, pwd);
        }

        public MovsProdSinRegINDUSAL_Service(string IDusuario, string pwd, string empresa)
        {
            // Constructor para trabajar contra los web services una vez obtenida la empresa de trabajo
            Entidades.Properties.Settings miConfig = new Entidades.Properties.Settings();
            this.Url = miConfig.urlInicioWS + "/" + empresa + "/Page/MovsProdSinRegINDUSAL?WSDL";
            if (miConfig.useDefCredts)
                this.UseDefaultCredentials = true;
            else
                this.Credentials = new NetworkCredential(IDusuario, pwd);
        }

        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;

        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;

        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;

        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;

        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;

        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;

        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;

        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/movsprodsinregindusal:Read", RequestNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", ResponseElementName = "Read_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("MovsProdSinRegINDUSAL")]
        public MovsProdSinRegINDUSAL Read(string Num_movimiento)
        {
            object[] results = this.Invoke("Read", new object[] {
                    Num_movimiento});
            return ((MovsProdSinRegINDUSAL)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginRead(string Num_movimiento, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Read", new object[] {
                    Num_movimiento}, callback, asyncState);
        }

        /// <remarks/>
        public MovsProdSinRegINDUSAL EndRead(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((MovsProdSinRegINDUSAL)(results[0]));
        }

        /// <remarks/>
        public void ReadAsync(string Num_movimiento)
        {
            this.ReadAsync(Num_movimiento, null);
        }

        /// <remarks/>
        public void ReadAsync(string Num_movimiento, object userState)
        {
            if ((this.ReadOperationCompleted == null))
            {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                    Num_movimiento}, this.ReadOperationCompleted, userState);
        }

        private void OnReadOperationCompleted(object arg)
        {
            if ((this.ReadCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/movsprodsinregindusal:ReadMultiple", RequestNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", ResponseElementName = "ReadMultiple_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public MovsProdSinRegINDUSAL[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] MovsProdSinRegINDUSAL_Filter[] filter, string bookmarkKey, int setSize)
        {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                    filter,
                    bookmarkKey,
                    setSize});
            return ((MovsProdSinRegINDUSAL[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginReadMultiple(MovsProdSinRegINDUSAL_Filter[] filter, string bookmarkKey, int setSize, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ReadMultiple", new object[] {
                    filter,
                    bookmarkKey,
                    setSize}, callback, asyncState);
        }

        /// <remarks/>
        public MovsProdSinRegINDUSAL[] EndReadMultiple(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((MovsProdSinRegINDUSAL[])(results[0]));
        }

        /// <remarks/>
        public void ReadMultipleAsync(MovsProdSinRegINDUSAL_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }

        /// <remarks/>
        public void ReadMultipleAsync(MovsProdSinRegINDUSAL_Filter[] filter, string bookmarkKey, int setSize, object userState)
        {
            if ((this.ReadMultipleOperationCompleted == null))
            {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                    filter,
                    bookmarkKey,
                    setSize}, this.ReadMultipleOperationCompleted, userState);
        }

        private void OnReadMultipleOperationCompleted(object arg)
        {
            if ((this.ReadMultipleCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/movsprodsinregindusal:IsUpdated", RequestNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", ResponseElementName = "IsUpdated_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key)
        {
            object[] results = this.Invoke("IsUpdated", new object[] {
                    Key});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginIsUpdated(string Key, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("IsUpdated", new object[] {
                    Key}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndIsUpdated(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void IsUpdatedAsync(string Key)
        {
            this.IsUpdatedAsync(Key, null);
        }

        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState)
        {
            if ((this.IsUpdatedOperationCompleted == null))
            {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                    Key}, this.IsUpdatedOperationCompleted, userState);
        }

        private void OnIsUpdatedOperationCompleted(object arg)
        {
            if ((this.IsUpdatedCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/movsprodsinregindusal:Create", RequestNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", ResponseElementName = "Create_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref MovsProdSinRegINDUSAL MovsProdSinRegINDUSAL)
        {
            object[] results = this.Invoke("Create", new object[] {
                    MovsProdSinRegINDUSAL});
            MovsProdSinRegINDUSAL = ((MovsProdSinRegINDUSAL)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCreate(MovsProdSinRegINDUSAL MovsProdSinRegINDUSAL, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Create", new object[] {
                    MovsProdSinRegINDUSAL}, callback, asyncState);
        }

        /// <remarks/>
        public void EndCreate(System.IAsyncResult asyncResult, out MovsProdSinRegINDUSAL MovsProdSinRegINDUSAL)
        {
            object[] results = this.EndInvoke(asyncResult);
            MovsProdSinRegINDUSAL = ((MovsProdSinRegINDUSAL)(results[0]));
        }

        /// <remarks/>
        public void CreateAsync(MovsProdSinRegINDUSAL MovsProdSinRegINDUSAL)
        {
            this.CreateAsync(MovsProdSinRegINDUSAL, null);
        }

        /// <remarks/>
        public void CreateAsync(MovsProdSinRegINDUSAL MovsProdSinRegINDUSAL, object userState)
        {
            if ((this.CreateOperationCompleted == null))
            {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                    MovsProdSinRegINDUSAL}, this.CreateOperationCompleted, userState);
        }

        private void OnCreateOperationCompleted(object arg)
        {
            if ((this.CreateCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/movsprodsinregindusal:CreateMultiple", RequestNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", ResponseElementName = "CreateMultiple_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)] ref MovsProdSinRegINDUSAL[] MovsProdSinRegINDUSAL_List)
        {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                    MovsProdSinRegINDUSAL_List});
            MovsProdSinRegINDUSAL_List = ((MovsProdSinRegINDUSAL[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCreateMultiple(MovsProdSinRegINDUSAL[] MovsProdSinRegINDUSAL_List, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CreateMultiple", new object[] {
                    MovsProdSinRegINDUSAL_List}, callback, asyncState);
        }

        /// <remarks/>
        public void EndCreateMultiple(System.IAsyncResult asyncResult, out MovsProdSinRegINDUSAL[] MovsProdSinRegINDUSAL_List)
        {
            object[] results = this.EndInvoke(asyncResult);
            MovsProdSinRegINDUSAL_List = ((MovsProdSinRegINDUSAL[])(results[0]));
        }

        /// <remarks/>
        public void CreateMultipleAsync(MovsProdSinRegINDUSAL[] MovsProdSinRegINDUSAL_List)
        {
            this.CreateMultipleAsync(MovsProdSinRegINDUSAL_List, null);
        }

        /// <remarks/>
        public void CreateMultipleAsync(MovsProdSinRegINDUSAL[] MovsProdSinRegINDUSAL_List, object userState)
        {
            if ((this.CreateMultipleOperationCompleted == null))
            {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                    MovsProdSinRegINDUSAL_List}, this.CreateMultipleOperationCompleted, userState);
        }

        private void OnCreateMultipleOperationCompleted(object arg)
        {
            if ((this.CreateMultipleCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/movsprodsinregindusal:Update", RequestNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", ResponseElementName = "Update_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref MovsProdSinRegINDUSAL MovsProdSinRegINDUSAL)
        {
            object[] results = this.Invoke("Update", new object[] {
                    MovsProdSinRegINDUSAL});
            MovsProdSinRegINDUSAL = ((MovsProdSinRegINDUSAL)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginUpdate(MovsProdSinRegINDUSAL MovsProdSinRegINDUSAL, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Update", new object[] {
                    MovsProdSinRegINDUSAL}, callback, asyncState);
        }

        /// <remarks/>
        public void EndUpdate(System.IAsyncResult asyncResult, out MovsProdSinRegINDUSAL MovsProdSinRegINDUSAL)
        {
            object[] results = this.EndInvoke(asyncResult);
            MovsProdSinRegINDUSAL = ((MovsProdSinRegINDUSAL)(results[0]));
        }

        /// <remarks/>
        public void UpdateAsync(MovsProdSinRegINDUSAL MovsProdSinRegINDUSAL)
        {
            this.UpdateAsync(MovsProdSinRegINDUSAL, null);
        }

        /// <remarks/>
        public void UpdateAsync(MovsProdSinRegINDUSAL MovsProdSinRegINDUSAL, object userState)
        {
            if ((this.UpdateOperationCompleted == null))
            {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                    MovsProdSinRegINDUSAL}, this.UpdateOperationCompleted, userState);
        }

        private void OnUpdateOperationCompleted(object arg)
        {
            if ((this.UpdateCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/movsprodsinregindusal:UpdateMultiple", RequestNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", ResponseElementName = "UpdateMultiple_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)] ref MovsProdSinRegINDUSAL[] MovsProdSinRegINDUSAL_List)
        {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                    MovsProdSinRegINDUSAL_List});
            MovsProdSinRegINDUSAL_List = ((MovsProdSinRegINDUSAL[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginUpdateMultiple(MovsProdSinRegINDUSAL[] MovsProdSinRegINDUSAL_List, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UpdateMultiple", new object[] {
                    MovsProdSinRegINDUSAL_List}, callback, asyncState);
        }

        /// <remarks/>
        public void EndUpdateMultiple(System.IAsyncResult asyncResult, out MovsProdSinRegINDUSAL[] MovsProdSinRegINDUSAL_List)
        {
            object[] results = this.EndInvoke(asyncResult);
            MovsProdSinRegINDUSAL_List = ((MovsProdSinRegINDUSAL[])(results[0]));
        }

        /// <remarks/>
        public void UpdateMultipleAsync(MovsProdSinRegINDUSAL[] MovsProdSinRegINDUSAL_List)
        {
            this.UpdateMultipleAsync(MovsProdSinRegINDUSAL_List, null);
        }

        /// <remarks/>
        public void UpdateMultipleAsync(MovsProdSinRegINDUSAL[] MovsProdSinRegINDUSAL_List, object userState)
        {
            if ((this.UpdateMultipleOperationCompleted == null))
            {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                    MovsProdSinRegINDUSAL_List}, this.UpdateMultipleOperationCompleted, userState);
        }

        private void OnUpdateMultipleOperationCompleted(object arg)
        {
            if ((this.UpdateMultipleCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/movsprodsinregindusal:Delete", RequestNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", ResponseElementName = "Delete_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key)
        {
            object[] results = this.Invoke("Delete", new object[] {
                    Key});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDelete(string Key, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Delete", new object[] {
                    Key}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndDelete(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void DeleteAsync(string Key)
        {
            this.DeleteAsync(Key, null);
        }

        /// <remarks/>
        public void DeleteAsync(string Key, object userState)
        {
            if ((this.DeleteOperationCompleted == null))
            {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                    Key}, this.DeleteOperationCompleted, userState);
        }

        private void OnDeleteOperationCompleted(object arg)
        {
            if ((this.DeleteCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal")]
    public partial class MovsProdSinRegINDUSAL
    {

        private string keyField;

        private string num_movimientoField;

        private Tipo_Movimiento tipo_MovimientoField;

        private bool tipo_MovimientoFieldSpecified;

        private string operarioField;

        private System.DateTime fechaField;

        private bool fechaFieldSpecified;

        private System.DateTime horaField;

        private bool horaFieldSpecified;

        private string maquinaField;

        private string num_lavadoField;

        private string programaField;

        private string cod_ClienteField;

        private string cod_Cte_FacturaField;

        private string productoField;

        private string num_serieField;

        private string codigo_facturacionField;

        private decimal cantidad_recibidaField;

        private bool cantidad_recibidaFieldSpecified;

        private decimal cantidad_enviarField;

        private bool cantidad_enviarFieldSpecified;

        private decimal cantidad_enviadaField;

        private bool cantidad_enviadaFieldSpecified;

        private string uDMField;

        private bool registradoField;

        private bool registradoFieldSpecified;

        private decimal num_HorasField;

        private bool num_HorasFieldSpecified;

        private string num_RutaField;

        private int linea_expedicionField;

        private bool linea_expedicionFieldSpecified;

        private bool en_FacturaField;

        private bool en_FacturaFieldSpecified;

        private string cod_carroField;

        private int num_carroField;

        private bool num_carroFieldSpecified;

        private bool carro_completoField;

        private bool carro_completoFieldSpecified;

        private string turnoField;

        private string num_pedidoField;

        private string nombre_rutaField;

        private string alias_clienteField;

        /// <comentarios/>
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <comentarios/>
        public string Num_movimiento
        {
            get
            {
                return this.num_movimientoField;
            }
            set
            {
                this.num_movimientoField = value;
            }
        }

        /// <comentarios/>
        public Tipo_Movimiento Tipo_Movimiento
        {
            get
            {
                return this.tipo_MovimientoField;
            }
            set
            {
                this.tipo_MovimientoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Tipo_MovimientoSpecified
        {
            get
            {
                return this.tipo_MovimientoFieldSpecified;
            }
            set
            {
                this.tipo_MovimientoFieldSpecified = value;
            }
        }

        /// <comentarios/>
        public string Operario
        {
            get
            {
                return this.operarioField;
            }
            set
            {
                this.operarioField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaSpecified
        {
            get
            {
                return this.fechaFieldSpecified;
            }
            set
            {
                this.fechaFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime Hora
        {
            get
            {
                return this.horaField;
            }
            set
            {
                this.horaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HoraSpecified
        {
            get
            {
                return this.horaFieldSpecified;
            }
            set
            {
                this.horaFieldSpecified = value;
            }
        }

        /// <comentarios/>
        public string Maquina
        {
            get
            {
                return this.maquinaField;
            }
            set
            {
                this.maquinaField = value;
            }
        }

        /// <comentarios/>
        public string Num_lavado
        {
            get
            {
                return this.num_lavadoField;
            }
            set
            {
                this.num_lavadoField = value;
            }
        }

        /// <comentarios/>
        public string Programa
        {
            get
            {
                return this.programaField;
            }
            set
            {
                this.programaField = value;
            }
        }

        /// <comentarios/>
        public string Cod_Cliente
        {
            get
            {
                return this.cod_ClienteField;
            }
            set
            {
                this.cod_ClienteField = value;
            }
        }

        /// <comentarios/>
        public string Cod_Cte_Factura
        {
            get
            {
                return this.cod_Cte_FacturaField;
            }
            set
            {
                this.cod_Cte_FacturaField = value;
            }
        }

        /// <comentarios/>
        public string Producto
        {
            get
            {
                return this.productoField;
            }
            set
            {
                this.productoField = value;
            }
        }

        /// <comentarios/>
        public string Num_serie
        {
            get
            {
                return this.num_serieField;
            }
            set
            {
                this.num_serieField = value;
            }
        }

        /// <comentarios/>
        public string Codigo_facturacion
        {
            get
            {
                return this.codigo_facturacionField;
            }
            set
            {
                this.codigo_facturacionField = value;
            }
        }

        /// <comentarios/>
        public decimal Cantidad_recibida
        {
            get
            {
                return this.cantidad_recibidaField;
            }
            set
            {
                this.cantidad_recibidaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cantidad_recibidaSpecified
        {
            get
            {
                return this.cantidad_recibidaFieldSpecified;
            }
            set
            {
                this.cantidad_recibidaFieldSpecified = value;
            }
        }

        /// <comentarios/>
        public decimal Cantidad_enviar
        {
            get
            {
                return this.cantidad_enviarField;
            }
            set
            {
                this.cantidad_enviarField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cantidad_enviarSpecified
        {
            get
            {
                return this.cantidad_enviarFieldSpecified;
            }
            set
            {
                this.cantidad_enviarFieldSpecified = value;
            }
        }

        /// <comentarios/>
        public decimal Cantidad_enviada
        {
            get
            {
                return this.cantidad_enviadaField;
            }
            set
            {
                this.cantidad_enviadaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cantidad_enviadaSpecified
        {
            get
            {
                return this.cantidad_enviadaFieldSpecified;
            }
            set
            {
                this.cantidad_enviadaFieldSpecified = value;
            }
        }

        /// <comentarios/>
        public string UDM
        {
            get
            {
                return this.uDMField;
            }
            set
            {
                this.uDMField = value;
            }
        }

        /// <comentarios/>
        public bool Registrado
        {
            get
            {
                return this.registradoField;
            }
            set
            {
                this.registradoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegistradoSpecified
        {
            get
            {
                return this.registradoFieldSpecified;
            }
            set
            {
                this.registradoFieldSpecified = value;
            }
        }

        /// <comentarios/>
        public decimal Num_Horas
        {
            get
            {
                return this.num_HorasField;
            }
            set
            {
                this.num_HorasField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Num_HorasSpecified
        {
            get
            {
                return this.num_HorasFieldSpecified;
            }
            set
            {
                this.num_HorasFieldSpecified = value;
            }
        }

        /// <comentarios/>
        public string Num_Ruta
        {
            get
            {
                return this.num_RutaField;
            }
            set
            {
                this.num_RutaField = value;
            }
        }

        /// <comentarios/>
        public int Linea_expedicion
        {
            get
            {
                return this.linea_expedicionField;
            }
            set
            {
                this.linea_expedicionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Linea_expedicionSpecified
        {
            get
            {
                return this.linea_expedicionFieldSpecified;
            }
            set
            {
                this.linea_expedicionFieldSpecified = value;
            }
        }

        /// <comentarios/>
        public bool En_Factura
        {
            get
            {
                return this.en_FacturaField;
            }
            set
            {
                this.en_FacturaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool En_FacturaSpecified
        {
            get
            {
                return this.en_FacturaFieldSpecified;
            }
            set
            {
                this.en_FacturaFieldSpecified = value;
            }
        }

        /// <comentarios/>
        public string Cod_carro
        {
            get
            {
                return this.cod_carroField;
            }
            set
            {
                this.cod_carroField = value;
            }
        }

        /// <comentarios/>
        public int Num_carro
        {
            get
            {
                return this.num_carroField;
            }
            set
            {
                this.num_carroField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Num_carroSpecified
        {
            get
            {
                return this.num_carroFieldSpecified;
            }
            set
            {
                this.num_carroFieldSpecified = value;
            }
        }

        /// <comentarios/>
        public bool Carro_completo
        {
            get
            {
                return this.carro_completoField;
            }
            set
            {
                this.carro_completoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Carro_completoSpecified
        {
            get
            {
                return this.carro_completoFieldSpecified;
            }
            set
            {
                this.carro_completoFieldSpecified = value;
            }
        }

        /// <comentarios/>
        public string Turno
        {
            get
            {
                return this.turnoField;
            }
            set
            {
                this.turnoField = value;
            }
        }

        /// <comentarios/>
        public string Num_pedido
        {
            get
            {
                return this.num_pedidoField;
            }
            set
            {
                this.num_pedidoField = value;
            }
        }

        /// <comentarios/>
        public string Nombre_ruta
        {
            get
            {
                return this.nombre_rutaField;
            }
            set
            {
                this.nombre_rutaField = value;
            }
        }

        /// <comentarios/>
        public string Alias_cliente
        {
            get
            {
                return this.alias_clienteField;
            }
            set
            {
                this.alias_clienteField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal")]
    public enum Tipo_Movimiento
    {

        /// <comentarios/>
        RECEPCION,

        /// <comentarios/>
        CONTEO,

        /// <comentarios/>
        LAVADORA,

        /// <comentarios/>
        TUNEL,

        /// <comentarios/>
        CALANDRA,

        /// <comentarios/>
        FELPA,

        /// <comentarios/>
        FORMA,

        /// <comentarios/>
        RECHAZO,

        /// <comentarios/>
        COSTURA,

        /// <comentarios/>
        OXIDO,

        /// <comentarios/>
        EXPEDICION,

        /// <comentarios/>
        SUBCONTRATACION,

        /// <comentarios/>
        DESAPRESTADO,

        /// <comentarios/>
        EMPAQUETADO,

        /// <comentarios/>
        PARTES,
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal")]
    public partial class MovsProdSinRegINDUSAL_Filter
    {

        private MovsProdSinRegINDUSAL_Fields fieldField;

        private string criteriaField;

        /// <comentarios/>
        public MovsProdSinRegINDUSAL_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }

        /// <comentarios/>
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:microsoft-dynamics-schemas/page/movsprodsinregindusal")]
    public enum MovsProdSinRegINDUSAL_Fields
    {

        /// <comentarios/>
        Num_movimiento,

        /// <comentarios/>
        Tipo_Movimiento,

        /// <comentarios/>
        Operario,

        /// <comentarios/>
        Fecha,

        /// <comentarios/>
        Hora,

        /// <comentarios/>
        Maquina,

        /// <comentarios/>
        Num_lavado,

        /// <comentarios/>
        Programa,

        /// <comentarios/>
        Cod_Cliente,

        /// <comentarios/>
        Cod_Cte_Factura,

        /// <comentarios/>
        Producto,

        /// <comentarios/>
        Num_serie,

        /// <comentarios/>
        Codigo_facturacion,

        /// <comentarios/>
        Cantidad_recibida,

        /// <comentarios/>
        Cantidad_enviar,

        /// <comentarios/>
        Cantidad_enviada,

        /// <comentarios/>
        UDM,

        /// <comentarios/>
        Registrado,

        /// <comentarios/>
        Num_Horas,

        /// <comentarios/>
        Num_Ruta,

        /// <comentarios/>
        Linea_expedicion,

        /// <comentarios/>
        En_Factura,

        /// <comentarios/>
        Cod_carro,

        /// <comentarios/>
        Num_carro,

        /// <comentarios/>
        Carro_completo,

        /// <comentarios/>
        Turno,

        /// <comentarios/>
        Num_pedido,

        /// <comentarios/>
        Nombre_ruta,

        /// <comentarios/>
        Alias_cliente,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public MovsProdSinRegINDUSAL Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((MovsProdSinRegINDUSAL)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public MovsProdSinRegINDUSAL[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((MovsProdSinRegINDUSAL[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public MovsProdSinRegINDUSAL MovsProdSinRegINDUSAL
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((MovsProdSinRegINDUSAL)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public MovsProdSinRegINDUSAL[] MovsProdSinRegINDUSAL_List
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((MovsProdSinRegINDUSAL[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public MovsProdSinRegINDUSAL MovsProdSinRegINDUSAL
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((MovsProdSinRegINDUSAL)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public MovsProdSinRegINDUSAL[] MovsProdSinRegINDUSAL_List
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((MovsProdSinRegINDUSAL[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}